const presupuestoDefaultTypes = {
    activity: [
        'Boda',
        'Cumpleaños',
        'Conferencia',
        'Feria',
        'Exposicion',
        'Comporativo',
        'Gala',
        'Festival',
        'Concierto',
        'Deportivo',
        'Graducacion',
    ],
    article: [
        'Comida',
        'Bebidas',
        'Decoración',
        'Mobiliario',
        'Sonido',
        'Iluminación',
        'Fotografía',
        'Video',
        'Entretenimiento',
        'Música',
        'Transporte',
        'Seguridad',
        'Catering',
        'Postres',
        'Tortas',
        'Flores',
        'Mesas',
        'Sillas',
        'Vajilla',
        'Cristalería',
        'Barra de Bebidas',
        'Invitaciones',
        'Vestimenta',
        'Traducción',
        'Hospedaje',
        'Impresión',
        'Diseño Gráfico',
        'Logística',
        'Asesoría',
        'Publicidad',
        'Audiovisuales',
        'Centros de Mesa',
        'Alquiler de Equipos',
        'Carpas y Toldos',
        'Escenografía',
        'Animación',
        'Regalos y Recuerdos',
        'Espacios de Eventos',
        'Efectos Especiales',
        'Personal de Apoyo',
        'Seguro de Eventos',
    ],
    statusPresupuesto: ['Aceptado', 'Editando', 'Rechazado', 'Completado'],
    statusPaid: ['Pendiente', 'Pago', 'No Pago'],
};

const proveedorDefaultTypes = [
    'Catering',
    'Banquete',
    'Decoración',
    'Alquiler de Mobiliario',
    'Floristería',
    'Fotografía',
    'Video',
    'Música',
    'Entretenimiento',
    'Iluminación',
    'Sonido',
    'Transporte',
    'Servicios de Seguridad',
    'Pastelería y Repostería',
    'Bebidas y Barra',
    'Servicios de Traducción',
    'Servicios de Hospedaje',
    'Servicios de Impresión',
    'Diseño Gráfico',
];

export { presupuestoDefaultTypes, proveedorDefaultTypes };
