const presupuestoDefaultTypes = {
    activity: [
        'Boda',
        'Cumpleaños',
        'Conferencia',
        'Feria',
        'Exposicion',
        'Comporativo',
        'Gala',
        'Festival',
        'Concierto',
        'Deportivo',
        'Graducacion',
    ],
    article: [
        'Comida',
        'Bebida',
        'Decoración',
        'Sonido',
        'Iluminación',
        'Mobiliario',
        'Personal',
        'Invitaciones',
        'Vestimenta',
        'Fotografía',
        'Entretenimiento',
        'Centros de Mesa',
        'Audiovisuales',
        'Catering',
        'Postres',
        'Tortas',
        'Flores',
        'Mesas',
        'Sillas',
        'Vajilla',
        'Cristalería',
        'Barra de Bebidas',
    ],
    statusPresupuesto: ['Aceptada', 'Editando', 'Rechazada', 'Completada'],
    statusPaid: ['Pendiente', 'Pago', 'No Pago'],
};

const proveedorDefaultTypes = [
    'Catering',
    'Banquete',
    'Decoración',
    'Alquiler de Mobiliario',
    'Floristería',
    'Fotografía',
    'Video',
    'Música',
    'Entretenimiento',
    'Iluminación',
    'Sonido',
    'Transporte',
    'Servicios de Seguridad',
    'Pastelería y Repostería',
    'Bebidas y Barra',
    'Servicios de Traducción',
    'Servicios de Hospedaje',
    'Servicios de Impresión',
    'Diseño Gráfico',
];

export { presupuestoDefaultTypes, proveedorDefaultTypes };
