const defaultTypesArray = {
    activity: [
        'Boda',
        'Cumpleaños',
        'Conferencia',
        'Feria',
        'Exposicion',
        'Corporativo',
        'Gala',
        'Festival',
        'Concierto',
        'Deportivo',
        'Graducacion',
    ],
    article: [
        'Alquiler de Equipos',
        'Animación',
        'Asesoría',
        'Audiovisuales',
        'Barra de Bebidas',
        'Bebidas',
        'Carpas y Toldos',
        'Catering',
        'Centros de Mesa',
        'Comida',
        'Cristalería',
        'Decoración',
        'Diseño Gráfico',
        'Efectos Especiales',
        'Entretenimiento',
        'Escenografía',
        'Espacios de Eventos',
        'Fotografía',
        'Flores',
        'Hospedaje',
        'Iluminación',
        'Impresión',
        'Invitaciones',
        'Logística',
        'Mesas',
        'Mobiliario',
        'Música',
        'Personal de Apoyo',
        'Postres',
        'Publicidad',
        'Regalos y Recuerdos',
        'Seguridad',
        'Seguro de Eventos',
        'Sillas',
        'Sonido',
        'Tortas',
        'Traducción',
        'Transporte',
        'Vajilla',
        'Vestimenta',
        'Video',
        'Otro',
    ],
    statusPresupuesto: ['Aceptado', 'Editando', 'Rechazado', 'Completado'],
    statusPaid: ['Pago', 'Pendiente', 'No Pago'],
};

export default defaultTypesArray;
